name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Get version from package.json before release step
        id: get_version_before_release
        run: echo "::set-output name=version::$(npm run get-version --silent)"

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: bot-flowbuild
          GIT_AUTHOR_EMAIL: bot.flowbuild@gmail.com
          GIT_COMMITTER_NAME: bot-flowbuilld
          GIT_COMMITTER_EMAIL: bot.flowbuild@gmail.com
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: npm run release

      - name: Get version from package.json after release step
        id: get_version_after_release
        run: echo "::set-output name=version::$(npm run get-version --silent)"

      - name: Create Pull Request with updated package files
        if: steps.get_version_before_release.outputs.version != steps.get_version_after_release.outputs.version
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'chore(release): ${{ steps.get_version_after_release.outputs.version }}'
          committer: bot-flowbuilld <bot.flowbuild@gmail.com>
          author: bot-flowbuilld <bot.flowbuild@gmail.com>
          title: 'chore(release): ${{ steps.get_version_after_release.outputs.version }}'
          body: 'Version bump in package.json and package-lock.json for release [${{ steps.get_version_after_release.outputs.version }}](https://github.com/${{github.repository}}/releases/tag/v${{ steps.get_version_after_release.outputs.version }})'
          branch: version-bump/${{ steps.get_version_after_release.outputs.version }}
