name: size
on: [pull_request]
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - uses: andresz1/size-limit-action@v1
        run: "echo ##[set-output name=ref;]$(git rev-parse --abbrev-ref HEAD)"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
